const Themes = {
  slate: {
    label: 'Slate',
    primary: '#f0f5f9',
    secondary: '#B0BBC3',
    accent: '#1e2022',
    isDark: false,
  },
  pizzaz: {
    label: 'Pizzaz',
    primary: 'white',
    secondary: 'lightgray',
    accent: 'purple',
    isDark: false,
  },
  razzle: {
    label: 'Razzle',
    primary: '#2c003e',
    secondary: '#fe346e',
    accent: '#d2fafb',
    isDark: true,
  },
  energy: {
    label: 'Energy',
    primary: '#230444',
    secondary: '#ed8240',
    accent: '#d2fafb',
    isDark: true,
  },
  cosmicBold: {
    label: 'Cosmic Bold',
    primary: '#110133',
    secondary: '#00918e',
    accent: '#ffdc34',
  },
  pacific: {
    label: 'Pacific',
    primary: '#ecfcff',
    secondary: '#b2fcff',
    accent: '#3e64ff',
    isDark: false,
  },
  spring: {
    label: 'Spring',
    primary: '#fdc7ff',
    secondary: '#ffffc2',
    accent: '#323edd',
    isDark: false,
  },
  forest: {
    label: 'Forest',
    primary: '#EDFEFF',
    secondary: '#ffebd9',
    accent: '#235952',
    isDark: false,
  },
  cottonCandy: {
    label: 'Cotton Candy',
    accent: '#E839FF',
    secondary: '#ffffff',
    primary: '#c2f0fc',
    isDark: false,
  },
  hacker: {
    label: 'Hacker',
    primary: '#042700',
    secondary: 'black',
    accent: '#18E900',
    isDark: true,
  },
  volcano: {
    label: 'Volcano',
    secondary: '#ffac41',
    primary: '#323232',
    accent: '#ff1e56',
    isDark: true,
  },
  sunrise: {
    label: 'Sunrise',
    primary: '#3fc5f0',
    accent: '#007944',
    secondary: '#ffdc34',
    isDark: false,
  },
  sunset: {
    label: 'Sunset',
    secondary: '#0f4c81',
    primary: '#1b262c',
    accent: '#ed6663',
    isDark: true,
  },
  sunshine: {
    label: 'Sunshine',
    primary: '#fdd365',
    secondary: '#FF4833',
    accent: '#fd2eb3',
    isDark: false,
  },
  wild: {
    label: 'Wild',
    primary: '#4d089a',
    accent: '#e8f044',
    secondary: '#dc2ade',
    isDark: true,
  },
  sporty: {
    label: 'Sport',
    primary: '#000f30',
    secondary: '#00e36b',
    accent: '#0083ff',
    isDark: true,
  },
  sportFlipped: {
    label: 'Sport Flipped',
    primary: '#000f30',
    accent: '#00e36b',
    secondary: '#0083ff',
    isDark: true,
  },
  sportFlopped: {
    label: 'Sport Flopped',
    primary: 'white',
    secondary: '#00e36b',
    accent: '#0083ff',
    isDark: false,
  },
  melon: {
    label: 'Melon',
    primary: '#ffa259',
    secondary: '#fa4252',
    accent: '#0c9463',
    isDark: false,
  },
};

module.exports = Themes;
